### ISSUE TITLE
Readme Container Link Invalid

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [Dynatrace/dynatrace-oneagent-operator#120]
The following files contain this comment: `defaults to docker.io/dynatrace/oneagent`
- https://github.com/Dynatrace/dynatrace-oneagent-operator/blob/master/deploy/cr.yaml
- https://github.com/Dynatrace/dynatrace-oneagent-operator/blob/master/pkg/apis/dynatrace/v1alpha1/defaults.go
- https://github.com/Dynatrace/dynatrace-oneagent-operator/blob/master/pkg/apis/dynatrace/v1alpha1/oneagent_types.go

Presumably this should be: https://hub.docker.com/r/dynatrace/oneagent

**Comment by Dynatrace-Adam-Gardner** [comment]
This also affects the current public documentation page: https://www.dynatrace.com/support/help/technology-support/cloud-platforms/openshift/installation-and-operation/full-stack/deploy-oneagent-on-openshift-container-platform/#expand-1553custom-resource-snippet

**Comment by lrgar** [comment]
Thank you Adam for your message. `docker.io` is the [official Docker registry](https://docs.docker.com/registry/introduction/#understanding-image-naming). The URL at ` https://hub.docker.com/` is referring to the web page with the image description, but not where the image itself is available from.
