### ISSUE TITLE
Multiple Operators on one cluster

### ISSUE THREAD

**Issue by pahofmann** [Dynatrace/dynatrace-oneagent-operator#126]
We have a scenario at a customer where one OpenShift cluster has dedicated worker nodes for different environments (DEV/QA/PROD)​. They should be separated into different dynatrace environments.

Ideally we would want to use the OneAgent operator, but that use case isn't supported as all agents deployed by the operator report to the same dynatrace environment. 

Would deploying multiple operators on the same cluster (adjusting their [ressource definitions](https://raw.githubusercontent.com/Dynatrace/dynatrace-oneagent-operator/master/deploy/openshift.yaml)), with node selectors corresponding to the relevant nodes work?

Or are there any inherent issues with running multiple OneAgent operators on the same cluster?

**Comment by baichinger** [comment]
Hi! No need to deploy multiple operators. OneAgent CRD supports a `nodeSelector` field for covering this use case.

-Bernhard

**Comment by namratachaudhary** [comment]
Hi, in addition to what @baichinger mentioned, you would need to deploy multiple cr.yaml pointing to desired dynatrace environment, with nodeslector field set. 

- Namrata

**Comment by namratachaudhary** [comment]
Hi, just to clarify what @baichinger  mentioned, you would need to deploy multiple cr.yaml pointing to desired Dynatrace environment, with nodeslector field set.
￼
-Namrata

**Comment by pahofmann** [comment]
Great, if deploying multiple custom resources is enough to satisfy the scenario that saves us a lot of overhead!  
Thanks for the quick help!
