### ISSUE TITLE
gitops tool argocd complains diff between OneAgent manifest in git and on k8s

### ISSUE THREAD

**Issue by tschonnie** [Dynatrace/dynatrace-oneagent-operator#133]
it seems that OneAgent changes its own manifest during installation.

```
env
  - name: ONEAGENT_INSTALLER_TOKEN
  - name: ONEAGENT_INSTALLER_SCRIPT_URL
  - name: ONEAGENT_INSTALLER_SKIP_CERT_CHECK
```
gets added  and
```
  skipCertCheck: false
  tolerations: []
```
gets deleted.

gitops tools by default always compare the manifest in the git repo with the manifest on k8s and if they diff they try to keep them in sync, which ends in an endless loop here.

Any idea why you change the manifest this way?

**Comment by lrgar** [comment]
Hello there,

As for why, we add some default environment variables by default that are then forwarded to the OneAgent pods. And as for the latter fields, they get omitted when stored if they have an "empty" value.

That being said, I can understand your use-case, and we can take it into consideration.

**Comment by tschonnie** [comment]
thank you so much! if I can do something to push this forward (open official support-case, doing some tests etc.) just let me know. as a workaround: is it possible to set those env variables myself in the manifest in the git repo so that everything is again in sync?

**Comment by lrgar** [comment]
Thanks, I've created an internal ticket.

As for a workaround, yes, I believe setting those environment variables explicitly, and removing the other two fields, `skipCertCheck` and `tolerations` should be enough (the values above are the default.) On the current Operator versions, those environment variables are more or less static, so it should be OK.
