### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vkamlesh** [Dynatrace/dynatrace-oneagent-operator#144]
I am following https://github.com/Dynatrace/dynatrace-oneagent-operator/tree/release-0.4.

Type: Managed

Release-v0.4

[ec2-user@ip-10-246-1-165 dynatrace]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-29T16:15:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-825e5d", GitCommit:"825e5de08cb05714f9b224cd6c47d9514df1d1a7", GitTreeState:"clean", BuildDate:"2019-08-18T03:58:32Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
[ec2-user@ip-10-246-1-165 dynatrace]

[ec2-user@ip-10-246-1-165 ~]$ kubectl get pods -n dynatrace
NAME                                           READY   STATUS             RESTARTS   AGE
dynatrace-oneagent-operator-568ddccbd4-pm27z   0/1     CrashLoopBackOff   822        2d22h

"level":"info","ts":1569832966.2025487,"logger":"oneagent.controller","msg":"istio: status","namespace":"dynatrace","name":"oneagent","enabled":true}
{"level":"info","ts":1569832966.2131538,"logger":"oneagent.controller","msg":"istio: creating VirtualService","namespace":"dynatrace","name":"oneagent","objectName":"5acf90dec5414f807bf277848c5b5ac4f92f2d04ce093c86fcc79a834c892e28","host":"10.223.1.30","port":9999,"protocol":"https"}
E0930 08:42:46.213323       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/istio.go:274
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/istio.go:234
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/istio.go:84
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/istio.go:52
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/oneagent_controller.go:142
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11428d8]

goroutine 203 [running]:
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x12c2760, 0x229a250)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent.(*ReconcileOneAgent).createIstioConfigurationForVirtualService(0xc000629900, 0xc0002fa400, 0xc000460260, 0x0, 0x1433d45, 0x7, 0x163ad80, 0xc000583da0, 0x9, 0xc000572200)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/istio.go:274 +0x188
github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent.(*ReconcileOneAgent).reconcileIstioCreateConfigurations(0xc000629900, 0xc0002fa400, 0xc000460260, 0xc00069dc88, 0x1, 0x1, 0x1433d45, 0x7, 0x163ad80, 0xc000583da0, ...)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/istio.go:234 +0x621
github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent.(*ReconcileOneAgent).reconcileIstioConfigurations(0xc000629900, 0xc0002fa400, 0xc000460260, 0xc00069dc88, 0x1, 0x1, 0x1433d45, 0x7, 0x163ad80, 0xc000583da0, ...)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/istio.go:84 +0xa1
github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent.(*ReconcileOneAgent).reconcileIstio(0xc000629900, 0x163ad80, 0xc000583da0, 0xc0002fa400, 0x162dfe0, 0xc000484e40, 0x8)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/istio.go:52 +0x26b
github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent.(*ReconcileOneAgent).Reconcile(0xc000629900, 0xc0004212f0, 0x9, 0xc0004212d0, 0x8, 0x22b0b60, 0xc000030000, 0x7ff0cc341b10, 0x133d760)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/oneagent_controller.go:142 +0xa63
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0006181e0, 0x0)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x1cc
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00056a440)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00056a440, 0x3b9aca00, 0x0, 0x20bde7364001, 0xc0003a9ce0)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00056a440, 0x3b9aca00, 0xc0003a9ce0)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x311

**Comment by namratachaudhary** [comment]
Hi @vkamlesh ,

We had identified the bug, and the fix is currently a work in progress #142 and shall be released soon.
Apologies for the inconvenience.

- Namrata

**Comment by namratachaudhary** [comment]
@vkamlesh - You may now download the version 0.4.2 available at https://github.com/Dynatrace/dynatrace-oneagent-operator/releases/tag/v0.4.2

Please open a new issue in case of further concerns :-)
