### ISSUE TITLE
Monitor Pod Level?

### ISSUE THREAD

**Issue by Gl4di4torRr** [Dynatrace/dynatrace-oneagent-operator#155]
Does the Dynatrace OneAgent Operator allow you to monitor each pod individually?

**Comment by lrgar** [comment]
Hello!

The Dynatrace Operator would install the full-stack OneAgent into your Kubernetes cluster nodes, who would then monitor your applications/pods that are running in such nodes. We do also provide alternatives and configuration options depending on your use case.

Is there something in particular you're looking for?

Best regards,
Luis

**Comment by Gl4di4torRr** [comment]
@lrgar We are not currently using the OneAgent Operator. I am interested to see if this will help us see what the request and limit is for each pod in a Kubernetes cluster. I understand the node level, but I am looking for pod level.

**Comment by estahn** [comment]
@Gl4di4torRr At the moment it will not provide you with this information.

https://answers.dynatrace.com/spaces/481/dynatrace/idea/229768/1st-class-kubernetes-support.html
