### ISSUE TITLE
Deprecated Extensions in OpenShift 4.x

### ISSUE THREAD

**Issue by jdziedzic** [Dynatrace/dynatrace-oneagent-operator#209]
OpenShift is reporting the following alert in versions 4.x due to multiple resources using v1beta1 API extensions.

"A client in the cluster is using deprecated extensions/v1beta1 API that will be removed soon."

**Comment by lrgar** [comment]
Hi there, thank you for letting us know.

May I ask which version of the Operator are you using? We removed our usages of the extensions/v1beta1 API around the Operator v0.4.0 I believe, unless we missed something.

Best regards,
Luis

**Comment by jdziedzic** [comment]
We are using Argo CD to manage the deployment of the OneAgent Operator. We are using the yaml files in the deploy/openshift directory in this project to create the operator. The majority of the resources in those files are still using betav1 extensions. We are currently using the registry.connect.redhat.com/dynatrace/dynatrace-oneagent-operator:v0.5.4 image, but I see that the current version of the deployment file is pointing to snapshot, should we be pointing to a snapshot version?

**Comment by lrgar** [comment]
Thanks. Don't think we have any "**extensions**/v1beta1" references anymore (i.e., PodSecurityPolicies are the only objects under this API we ever used IIRC) but we do have some other v1beta* objects. Regardless, will spin up a OCP4 environment and take a look.

As for the deployment manifests, please don't, that image is for our development builds. We've recently started to publish our release manifests as attachments for releases: https://github.com/Dynatrace/dynatrace-oneagent-operator/releases

**Comment by jdziedzic** [comment]
Thanks for pointing me to the releases, we'll switch to using OpenShift.yaml. I took a quick look at that file and see a few betav1 references in there as well, not sure if those particular extensions are being deprecated yet, but I will deploy and test.

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding

**Comment by lrgar** [comment]
Hello, apologies for the late reply. I've confirmed that we don't have any warnings for our latest manifests on OCP 4.3.

And as for the RBAC objects, indeed they are also deprecated although Kubernetes/OCP seem to handle them without any issues. Will try to update them regardless. 

Hopefully this should be all, and thanks for bringing this up to our attention. If you have any issues with the current manifests please let us know.

Luis
