### ISSUE TITLE
Documentation refers to operator version 0.7.0

### ISSUE THREAD

**Issue by leonvzGit** [Dynatrace/dynatrace-oneagent-operator#221]
The documentation: https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/oneagent-on-full-stack/deploy-oneagent-aks/#expand-1515operator

Refers to version 0.7.0, but there is no 0.7.0 release yet and when installing :  $ LATEST_RELEASE=$(curl -s https://api.github.com/repos/dynatrace/dynatrace-oneagent-operator/releases/latest | grep tag_name | cut -d '"' -f 4)
returns v0.6.0
Is this correct?, where do I get v0.7.0

**Comment by lrgar** [comment]
Hello, the version 0.7.0 will be released soon (probably tomorrow), but had the documentation updated first.

Best regards,
Luis

**Comment by leonvzGit** [comment]
thanks

**Comment by lrgar** [comment]
The Operator v0.7.0 has been released.
