### ISSUE TITLE
The Operator proxy configuration

### ISSUE THREAD

**Issue by leonvzGit** [Dynatrace/dynatrace-oneagent-operator#222]
Good Day, 
To get the k8s endpoint address you describe:
kubectl exec -n dynatrace -it deployments/dynatrace-oneagent-operator -- env | grep KUBERNETES_PORT_443_TCP_ADDR
KUBERNETES_PORT_443_TCP_ADDR=10.0.48.1

Does it make a difference when the k8s endpoint is exposed on 6443 and not 443?

**Comment by lrgar** [comment]
Hello. No, it shouldn't. Only the hostname/IP should be added to NO_PROXY.

**Comment by leonvzGit** [comment]
Ok but from the Operator log it explicitly times out on 443: Where do I sett it to rather connect to 6443?

{"level":"info","ts":"2020-03-22T14:40:02.805Z","logger":"cmd","msg":"Go Version: go1.13.6"}
{"level":"info","ts":"2020-03-22T14:40:02.805Z","logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":"2020-03-22T14:40:02.805Z","logger":"cmd","msg":"Version of operator-sdk: v0.12.0"}
{"level":"info","ts":"2020-03-22T14:40:02.805Z","logger":"cmd","msg":"Version of dynatrace-oneagent-operator: v0.6.0"}
{"level":"info","ts":"2020-03-22T14:40:02.805Z","logger":"leader","msg":"Trying to become the leader."}
{"level":"error","ts":"2020-03-22T14:40:32.806Z","logger":"cmd","msg":"","error":"Get https://158.2.0.1:443/api?timeout=32s: dial tcp 158.2.0.1:443: i/o timeout","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/cmd/manager/main.go:62\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

**Comment by lrgar** [comment]
In this case, the Operator is trying to query 158.2.0.1 for the Kubernetes API, so could you please add that one to NO_PROXY?

**Comment by leonvzGit** [comment]
ok in the cr.yaml or Kubernetes.yaml ?

**Comment by lrgar** [comment]
This is for the Operator pod, so kubernetes.yaml

**Comment by lrgar** [comment]
If there are no further questions, will close this ticket. Note that v0.7.0 was released last week so you can now configure the proxy on the OneAgent CR directly.
