### ISSUE TITLE
missing filesystem /opt

### ISSUE THREAD

**Issue by MarcoSchaar** [Dynatrace/dynatrace-oneagent-operator#224]
Hi,
while trying to apply latest version on kubernetes 

"Dynatrace OneAgent is being deployed as a container but /opt does not exist in host's filesystem"

**Comment by DTMad** [comment]
Hey!
Where did you deploy the operator? Vanilla kubernetes or something like GKE?

**Comment by MarcoSchaar** [comment]
Hej,
we use standard CoreOS.
with a former version (0.5.4) or installer.version 1.187.155.20200304-124853 it still works but installing from scratch fails

**Comment by DTMad** [comment]
Hey,
Ok - thanks!
May I ask which container runtime you use? Is it docker or do you use CRI-O?

**Comment by MarcoSchaar** [comment]
ah ok,
Container Linux by CoreOS 2345.3.0 (Rhyolite)   4.19.106-coreos   
docker://18.6.3
kubernetes v1.15.2

**Comment by DTMad** [comment]
Ok thanks!
Could you please try to add this to the custom resource and apply it again?
 
env:
  - name: ONEAGENT_ENABLE_VOLUME_STORAGE
    value: "true"

**Comment by MarcoSchaar** [comment]
Thanks a lot!
this parameter has fixed the issue.
