### ISSUE TITLE
Installation Argument Issue

### ISSUE THREAD

**Issue by PsychoSid** [Dynatrace/dynatrace-oneagent-operator#225]
Hi,

Trying to deploy the "OneAgent" CRD with the following:-
```
spec:
  args:
  - --set-host-group=my_host_group
  - --set-app-log-content-access=1
```

Logs show:
```
16:48:37 Error: Error: Unrecognized parameter "--set-app-log-content-access=1"
```

Have I malformed the YAML, or have I somehow typed the arg wrong ? This is with v0.7.0 of the operator, and v1.137.1000 of the agent.

Thanks.

**Comment by lrgar** [comment]
Hello there,

1.37.1000 is the version of the OneAgent image, which is different from the OneAgent version itself. Anyway, I presume you're using a version of the OneAgent before that argument was added, and replacing the arguments with,

```
spec:
  args:
  - HOST_GROUP=my_host_group
  - APP_LOG_CONTENT_ACCESS=1
```
should do.

**Comment by PsychoSid** [comment]
I will try but this doc https://www.dynatrace.com/support/help/technology-support/operating-systems/linux/installation/customize-oneagent-installation-on-linux/ says those argument types are deprecated ?

**Comment by lrgar** [comment]
Indeed. But they were added to the installer on OneAgent 1.185 I think. If you're using an older version of the OneAgent then you need the old argument names.

Can check the OneAgent version on the logs of the OneAgent pods to confirm?

**Comment by PsychoSid** [comment]
Ah ha - 

```
2020-03-30 17:18:45.392 UTC [6ce44d5f] info    main: Dynatrace Watchdog version: 1.183.150.20200121-122833 - built 2020.01.21 12:28:33, SCM Rev. b0638c9669b58d5bff339d34fc90078da220f3c8
```

that explains it, sorry I thought we had a later version I thought it was embedded but it downloads from the backend (new to me this !)

**Comment by PsychoSid** [comment]
Thanks very much

**Comment by lrgar** [comment]
No problem.
