### ISSUE TITLE
GCP - Incorrect stackdriver severity 

### ISSUE THREAD

**Issue by kaefferlein** [Dynatrace/dynatrace-oneagent-operator#277]
Hi all,

I use version 0.8.0 of the dynatrace onagent operator on a kubernetes cluster within the GCP.

After having a look at the logs within stackdriver I noticed, that all logs are being displayed as error logs - even though they are at INFO log level:

See example:
![image](https://user-images.githubusercontent.com/38203192/85836953-b8682880-b797-11ea-9c44-9f3f5cad149c.png)

Please also set a severity level to have the correct logging in stackdriver (https://stackoverflow.com/questions/43208878/how-does-stackdriver-logging-assert-the-severity-of-an-entry) 

Thanks & best regards
Anna

**Comment by lrgar** [comment]
Hi, thank you for letting us know. Will take a look.

Best regards,
Luis

**Comment by kaefferlein** [comment]
Hi,
any updates on this?

**Comment by lrgar** [comment]
Hi. Apologies for the delay, we were able to confirm the problem, and have a ticket in our backlog but haven't touched it yet.
