### ISSUE TITLE
Feature Request: Add Prometheus / OpenTelemetry metrics

### ISSUE THREAD

**Issue by merlindorin** [Dynatrace/dynatrace-oneagent-operator#280]
In our infrastructure, we use massively Dynatrace for our projects but we use Prometheus for our infrastructure.

It is possible to expose One Agent Operator metrics?

**Comment by lrgar** [comment]
Hi, thank you for your request. What would you be interested in? I imagine things related to the health of the Operator and OneAgent Pods?

Best regards,
Luis

**Comment by merlindorin** [comment]
Hi, thx for the quick response.

At the beginning, just basic metrics like health, concurrent pods, go related metrics, etc. But not only. We also need "business metrics" to monitor one agent operator services (concurrent connexion' etc).

I didn't check the code and I'm not a Dynatrace expert so I'm not aware on which metrics should be exposed but a better observability (with Grafana for example) is just better 😄. (Basically, we grab all the metrics we can and during production, we analyse and monitor some metrics at an higher level and put new alerts to prevent the next "disaster").

And to be honest, Dynatrace is used in our beta clusters (we have something like 100 projects) and we will be more confident to put Dynatrace in our production clusters (with an higher level of risk and far more projects) with a better observability.

**Comment by merlindorin** [comment]
oh nice, while we are auditing... we just saw we already have `/metrics` <3

<img width="934" alt="Screenshot 2020-08-06 at 12 07 26" src="https://user-images.githubusercontent.com/2074733/89520072-9d002c80-d7dd-11ea-91cc-fdfd01a5a330.png">

thx

**Comment by lrgar** [comment]
Well, partly, if you use v0.8.0 for example, there is new webhook Pod that currently doesn't publish any metrics. We'll take a proper look internally. Thank you for your feedback.

Best regards,
Luis
