### ISSUE TITLE
Feature Request : Labels

### ISSUE THREAD

**Issue by merlindorin** [Dynatrace/dynatrace-oneagent-operator#283]
Hi guyes, it's me again ^^.

Not related directly to the Dynatrace One Agent Operator (from my point of view) and more related to one Agent Operator.

It is possible to send more kubernetes data and more exactly "labels"? Right know, we only rely on namespace but we preferred to use "labels". I know we can grab labels using the Kubernetes API but due to security limitation, we can't provide external access to our cluster.

For example this is what we have:

<img width="131" alt="Screenshot 2020-08-04 at 13 46 09" src="https://user-images.githubusercontent.com/2074733/89290411-1cb0be80-d659-11ea-8c18-f59d6d1041c1.png">

**Comment by DTMad** [comment]
Hey @merlindorin ,

This is already possible as of now.
Check out our documentation here:
https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/other-deployments-and-configurations/leverage-tags-defined-in-kubernetes-deployments/

Hope this helps!

Regards,
Marco

**Comment by merlindorin** [comment]
hey @DTMad , thx for the answer.

From what the doc say... we have nothing to do for grabbing these tags. But we still don't have any label in tags :/.

Are you sure that one-agent will grab these labels and not Dynatrace itself using the Kubernetes API?

For memo, this is our tags (kubernetes section) :

![image](https://user-images.githubusercontent.com/2074733/89386009-c5febf80-d700-11ea-8202-e0ba9b582ee5.png)

**Comment by lrgar** [comment]
Hi! You need to grant the view role to the Service Accounts used by your Pods (see https://www.dynatrace.com/support/help/shortlink/kubernetes-tagging#grant-viewer-role-to-service-accounts) to use this feature.

Nonetheless, we're also working on improving the experience with Kubernetes and Dynatrace, including your security concerns and these labels.

Best regards,
Luis
