### ISSUE TITLE
Make Webhook Optional

### ISSUE THREAD

**Issue by gunnypatel** [Dynatrace/dynatrace-oneagent-operator#291]
Is it possible to disable the webhook? We don't plan on using the AppOnly deployment option so we'd like to disable the webhook associated with it. It'll be one less thing running in the cluster.

**Comment by gunnypatel** [comment]
After posting this I realized I can just update our deployment yaml file. That's probably the best option since the operator is deployed using raw yaml.

Just want to confirm that not running those pieces won't break anything else.

**Comment by lrgar** [comment]
Hi,

Yes, that is correct, for v0.8.0 (it may be different for future versions), you can delete the webhook deployment or scale it down to 0 for stopping it from running, and it doesn't affect other components.

Best regards,
Luis
