### ISSUE TITLE
Kubernetes for application-only monitoring not working as expected.

### ISSUE THREAD

**Issue by PavanVasist** [Dynatrace/dynatrace-oneagent-operator#309]
We have a scenario where we do not want to monitor workloads in particular namespace. So we tried the feature mentioned in the [blog](https://www.dynatrace.com/support/help/shortlink/kubernetes-applications#integrate-oneagent-into-your-application).

We created the custom resource **oneagentAPM** and annotated the namespace with _`oneagent.dynatrace.com/inject: "false"`_ But Still we see pods in that namespace are getting monitored.

The oneagentAPM has been deployed with the name 
> oneagent

![image](https://user-images.githubusercontent.com/13401050/91707010-d50c4c80-eb9c-11ea-81b5-4be680660615.png)

The below image shows the label and annotation added to a particular namespace - 

> hisptershop

![image](https://user-images.githubusercontent.com/13401050/91706112-8dd18c00-eb9b-11ea-8e15-273179ce32bb.png)

After adding the above configurations, we deployed an nginx pod into the cluster - 

![image](https://user-images.githubusercontent.com/13401050/91707186-17358e00-eb9d-11ea-9aaa-73c8e4369ba5.png)

As we see, the pod is still being shown as monitored in DT cluster, whereas it should not have been the case. Can you please help us understand any further configurations which we are missing.

**Comment by lrgar** [comment]
Hello, just to confirm, you also have full-stack monitoring through an OneAgent (not OneAgentAPM) CR, is that correct?

At the moment, OneAgentAPM and OneAgent objects use different means of injection, and the OneAgent CR will inject into everything running on the Nodes on which it has been deployed, regardless of the configuration made for OneAgentAPM.

If you want to avoid monitoring an specific namespace, I believe you can use Container monitoring rules. I'd suggest contacting our Dynatrace Support team for further help.

Best regards,
Luis

**Comment by ferdinand0123** [comment]
Thank you will look into that matter.

**Comment by ferdinand0123** [comment]
Monitoring successfull.
