### ISSUE TITLE
OneAgent Operator not tracking requests between services on Kubernetes when using complete dns

### ISSUE THREAD

**Issue by gabrielplemos** [Dynatrace/dynatrace-oneagent-operator#319]
Using the OneAgent Operator on a k8s cluster, I was not able to see the interactions between the monitored services using the complete dns, i.e. http://svc-name.namespace.svc.cluster.local:port, only when using the short dns, i.e http://svc-name:port, to communicate between the services.

The infrastructure of the application is composed of microservices and the communication between the different uServices uses ClusterIP Services. Before changing the url to the short dns, only the requests to the first service were being monitored by Dynatrace, the other requests didn't appear either on the Service Flow Page or the Pure Path. After changing the url to the short dns all the requests started appearing on these pages.

I am not sure if this is the expected behavior, however I would like to report it even if only to help other people that have the same problem in the future.

**Comment by lrgar** [comment]
Hi. Thank you for your message, and apologies for the late reply. Could you please create an issue for our Dynatrace Support team about this problem, so that it can get redirected to the appropriate team.

Best regards,
Luis
