### ISSUE TITLE
Dynatrace incompatible with CIS health check dictatated configuration of logging directory

### ISSUE THREAD

**Issue by relyt0925** [Dynatrace/dynatrace-oneagent-operator#342]
The one agent deployment fails with
```
14:51:06 Started agent deployment as a container, PID 164480.
14:51:06 Downloading agent to /tmp/Dynatrace-OneAgent-Linux.sh via https://qyr08949.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=***&arch=x86&flavor=default
14:51:07 Download was skipped as the agent version did not change
14:51:07 Verifying agent installer signature
14:51:10 Verification successful
14:51:10 Deploying to: /mnt/host_root
14:51:10 Starting installer...
14:51:11 Checking root privileges...
14:51:11 OK
14:51:11 Error: Insufficient access rights (drwxr-x---) on: /var/log
14:51:11 Error: /var/log path must be globally traversable (--x permissions for others).
14:51:11 Error: Please adjust the permissions and then retry the installation.
```

When deployed in an environment that conforms to CIS health checks. The specific health check that causes this failure is
`Ensure permissions on all logfiles are configured`

![Screen Shot 2020-11-11 at 6 32 17 PM (1)](https://user-images.githubusercontent.com/7716924/99405373-5036f200-28b2-11eb-99e0-427fd9667985.png)

It is a part of health checks for all operating systems. That list for Ubuntu 18.04 is below:
[CIS_Ubuntu_Linux_18.04_LTS_Benchmark_v2.0.1.pdf](https://github.com/Dynatrace/dynatrace-oneagent-operator/files/5554233/CIS_Ubuntu_Linux_18.04_LTS_Benchmark_v2.0.1.pdf)

Managed offerings under compliance regulations (IKS for example) require this check be implemented to maintain their audit posture.

Dynatrace should remove this check or at least account for the situation where the log directory is permissions `740`

**Comment by lrgar** [comment]
Hello. Could you please create a ticket with our Dynatrace Support team so that it can be assigned to the corresponding team?

**Comment by relyt0925** [comment]
@Irgar a couple people have: We just wanted something to be able to point to that all can see without needing access to a specific account for the customer ticket.

**Comment by niteenkole** [comment]
We also see same issue and cannot use Dynatrace in our IBM managed IKS due to this.

@lrgar any update on this ?

**Comment by lrgar** [comment]
Hi @niteenkole - yes, you can configure the directory on which the OneAgent will be installed by modifying the OneAgent CR (cr.yaml), and adding two environment variables.

```yaml
...
spec:
  ...
  env:
    - name: ONEAGENT_ENABLE_VOLUME_STORAGE
      value: "true"
    - name: ONEAGENT_CONTAINER_STORAGE_PATH
      value: "/path/to/install"
```

On which case, the OneAgent data, including logs, will be installed inside the chosen directory. I'm not familiar with the IKS file system to recommend a directory however.

Will close this ticket, since this is how the original issue was solved as well. If you have further questions please let us know.

**Comment by relyt0925** [comment]
@irgar I was talking with Niteen and I believe you don't actually need to have this check
```
14:51:11 Checking root privileges...
14:51:11 OK
14:51:11 Error: Insufficient access rights (drwxr-x---) on: /var/log
14:51:11 Error: /var/log path must be globally traversable (--x permissions for others).
14:51:11 Error: Please adjust the permissions and then retry the installation.
```

If you are running with root permissions. Just more of an FYI in case it influences anything y'all do in the future

**Comment by niteenkole** [comment]
I dont think so that works for kubernetes as per  

https://answers.dynatrace.com/questions/228049/can-i-change-install-path-for-oneagent-dir-on-kube.html

**Comment by niteenkole** [comment]
I also tried multiple paths it fails .....

**Comment by lrgar** [comment]
> I was talking with Niteen and I believe you don't actually need to have this check

As I understand, it's requirement for the OneAgent to work. I suggest contacting our Dynatrace Support team if you want to reach the relevant team/PM.

> I dont think so that works for kubernetes as per
> https://answers.dynatrace.com/questions/228049/can-i-change-install-path-for-oneagent-dir-on-kube.html

I mentioned the steps described by Alois there. The `INSTALL_PATH` argument won't help you since it targets a different use case, but the steps I described through the two environment variables should (and don't set `INSTALL_PATH`)

Can you confirm that you are following the steps I mentioned and you still have issues?

**Comment by niteenkole** [comment]
Yes I did test with options and all other paths, it fails now its not able to see config files also.

  env:
    - name: ONEAGENT_ENABLE_VOLUME_STORAGE
      value: "true"
    - name: ONEAGENT_CONTAINER_STORAGE_PATH
      value: "/opt/dynatrace/oneagent"

regarding contacting your support its going for long :)
https://support.dynatrace.com/supportportal/browse/SUP-64779

**Comment by lrgar** [comment]
Thanks, I see.

`/opt/dynatrace/oneagent` is probably a bad directory though. `/opt` can be a better choice, a subdirectory will be created to have things inside.

I don't know which container runtime is used by IKS but, if it's Docker, you can also remove the `ONEAGENT_CONTAINER_STORAGE_PATH` environment variable as well, and a Docker volume will be used instead.

**Comment by relyt0925** [comment]
IKS uses containerd as it's runtime

**Comment by niteenkole** [comment]
Hi,

Yes agents are coming up..
  env:
    - name: ONEAGENT_ENABLE_VOLUME_STORAGE
      value: "true"
    - name: ONEAGENT_CONTAINER_STORAGE_PATH
      value: "/opt"

NAME                                           READY   STATUS    RESTARTS   AGE
dynatrace-oneagent-operator-6b7dd698c6-g8nbq   1/1     Running   0          28m
dynatrace-oneagent-webhook-6bf989bcd6-kqhtw    2/2     Running   0          28m
oneagent-27lsp                                 1/1     Running   0          2m27s
oneagent-5s2gj                                 1/1     Running   0          28m
oneagent-8g9d9                                 1/1     Running   0          28m
oneagent-c4hm8                                 1/1     Running   0          28m
oneagent-dnjl8                                 1/1     Running   0          28m
oneagent-jddg4                                 1/1     Running   0          28m
