### ISSUE TITLE
Oneagent pods are crashing with unknown flag error

### ISSUE THREAD

**Issue by snehakpersistent** [Dynatrace/dynatrace-oneagent-operator#372]
Dynatrace oneagent pods are crashing due to error:
`# oc logs pod/oneagent-4stwk
unknown flag: --set-app-log-content-access
Usage of dynatrace-oneagent-operator:
unknown flag: --set-app-log-content-access
      --cert string        File name for the public certificate. (default "tls.crt")
      --cert-key string    File name for the private key. (default "tls.key")
      --certs-dir string   Directory to look certificates for. (default "/mnt/webhook-certs")`

This flag is being used in installation script https://github.com/Dynatrace/dynatrace-operator/blob/5aa6efc16fd822a1382a15353378eb8d070b4cc7/deploy/install.sh#L106
Is it not supported anymore?

Dynatrace oneagent operator version: Built with latest master changes
Dynatrace operator version: Built with latest master changes

Cmd used for building oneagent and dynatrace operator image:
`./build/deploy.sh`

Cmd used to create artefacts(openshift.yaml/kubernetes.yaml):
`./build/release.sh`

Cmd used to deploy dynatrace operator:
`./deploy/install.sh --api-url <api_url> --api-token <api_token> --paas-token <paas_token> --enable-app-log-access --enable-k8s-monitoring --openshift`

**Comment by lrgar** [comment]
Hi. Please use our stable install.sh script available on the [dynatrace-operator](https://github.com/Dynatrace/dynatrace-operator/releases) releases: [install.sh|https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.1.0/install.sh]. They are pointing to the latest official release manifests and images, so they should be stable.

Master builds are used for development and may just break from time to time.
