### ISSUE TITLE
update base image to newest ubi-minimal

### ISSUE THREAD

**Issue by jkleinlercher** [Dynatrace/dynatrace-oneagent-operator#387]
dynatrace-oneagent-operator still uses obi-minimal 8.3:

https://github.com/Dynatrace/dynatrace-oneagent-operator/blob/f695d2626379c72fea077261bc1087a63e8a6a44/Dockerfile#L1

Redhat suggests updating this image because it has several security vulnerabilities:

https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.3&push_date=1618946153000&container-tabs=security

I would highly appreciate if dynatrace can do regular updates to their used base image. Thank you so much!

**Comment by DTMad** [comment]
Done
https://github.com/Dynatrace/dynatrace-oneagent-operator/pull/389
