### ISSUE TITLE
New release with latest commit

### ISSUE THREAD

**Issue by narora138** [Dynatrace/dynatrace-oneagent-operator#411]
We have an issue with the current mutating webhook and require it update its version to v1. There is a [commit]( https://github.com/Dynatrace/dynatrace-oneagent-operator/pull/405) that was already pulled into the master branch for this, but it was not put into a release. We would like to please have this in a release. We have lost K8s monitoring in our clusters because of this issue. Until bottlerocket OS is supported by Dynatrace, we cannot move to the newest operator.

**Comment by luhi-DT** [comment]
Hi, as this operator is deprecated there will be no new release to it. However the new [dynatrace-operator](https://github.com/Dynatrace/dynatrace-operator) is capable of doing everything the old oneagent-operator did aswell, so Bottlerocket OS should also work with classicFullStack in the dynatrace-operator. Only cloudNativeFullStack currently has the limitation with the CSI Driver not yet running on that OS (we currently work on removing that limitation).

**Comment by narora138** [comment]
@luhi-DT  Are we able to store the image of the oneagent codemodule in a private ECR with the new dynatrace-operator?
