### ISSUE TITLE
Clarification on required tokens

### ISSUE THREAD

**Issue by makentenza** [Dynatrace/dynatrace-oneagent-operator#43]
According to the instructions 2 different tokens are required for this to be deployed, API Token and PaaS Token. I've successfully tested the deployment using just the PaaS Token all the time. Why are these 2 different tokens required?

**Comment by oybed** [comment]
@makentenza I believe this helps explain your question re: the two tokens:
https://www.dynatrace.com/support/help/shortlink/id-and-token#access-tokens

**Comment by aloismayr** [comment]
Hi @makentenza,
The two tokens serve two different purposes. While the PaaS token is for the download and configuration of OneAgent on the nodes, the API token is used by the operator to access the Dynatrace API. The operator needs the API token for lifecycle management of the OneAgents with the cluster.

**Comment by makentenza** [comment]
Great, thanks @aloismayr for the clarification on this.
