### ISSUE TITLE
OpenShift: Error from server (BadRequest)

### ISSUE THREAD

**Issue by rsoulard** [Dynatrace/dynatrace-oneagent-operator#52]
When using 

`$ oc create -f https://raw.githubusercontent.com/Dynatrace/dynatrace-oneagent-operator/master/deploy/openshift.yaml`

as per the instructions in the [README.md](https://github.com/Dynatrace/dynatrace-oneagent-operator/blob/master/README.md) file, the command returns the following error:
`Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/Dynatrace/dynatrace-oneagent-operator/master/deploy/openshift.yaml": Deployment in version "v1" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v1"
unable to recognize "https://raw.githubusercontent.com/Dynatrace/dynatrace-oneagent-operator/master/deploy/openshift.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
`

It seems that this prevents the complete installation of the operator, which is also preventing me from viewing the logs.

**Environment Info**

- OS: UBUNTU 16.04 VM
- OC/OpenShift: v3.6.0+c4dd4cf
- Kubernetes: v1.6.1+5115d708d7

**Comment by baichinger** [comment]
Hi @rsoulard,

The operator is supported on Kubernetes 1.9 and OpenShift 3.9 or any newer version. Previous versions lack support for `CustomResourceDefinitions`.

**Comment by rsoulard** [comment]
Thanks for clearing that up.
