### ISSUE TITLE
apiToken and paasToken clarification

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [Dynatrace/dynatrace-oneagent-operator#54]
Request to improve the documentation. `apiToken` and `paasToken` are referenced but it's not documented anywhere how / where we get these from.

Also, what permissions do each token need?

Related to #43

**Comment by esukram** [comment]
Hi @Dynatrace-Adam-Gardner .

We to improve the Dynatrace API integration. The first idea is to only have one API token, that will be used to create a token for downloading the agent. So the user will only need to specify only one.

We will update the documentation to clarify the exact terminology.

Markus

**Comment by DTMad** [comment]
Hey!

I hope this documentation helps:
https://www.dynatrace.com/support/help/reference/dynatrace-concepts/access-tokens/

In case there are any open questions feel free to reopen the issue.

Regards,
Marco

**Comment by Dynatrace-Adam-Gardner** [comment]
Hi Marco,

Allow me to clarify. This sentence in the readme tells me to create a DT API key and PaaS token: `Create access tokens of type Dynatrace API and Platform as a Service and use its values in the following commands respectively`

However, as a new user of Dynatrace, I wouldn't know, from that description, which of these permissions to choose when creating my API token.

![image](https://user-images.githubusercontent.com/13639658/81132379-93beb400-8f91-11ea-8e1c-a848c94ceb58.png)

My suggestion is to explicitly state the required permissions so it's "foolproof".

**Comment by DTMad** [comment]
Ah now I get what you meant!
Thanks for the clarification @Dynatrace-Adam-Gardner !
Created an internal ticket to improve the documentation and the readme so we can support customers better to get the operator running!

Regards,
Marco

**Comment by mreider** [comment]
So if you look at this page [1] it states that you need "Access problem and event feed, metrics, and topology." Is this not sufficient?

https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/oneagent-with-helm/

**Comment by Dynatrace-Adam-Gardner** [comment]
It's not that the official doc is lacking, it's just a minor point that the doc in this repo could be improved from a usability standpoint by adding the permissions required.

I've seen it where customers Google "dynatrace oneagent operator", come straight to this repo then have to go back to the docs page and dig around for hte required permissions. From an ease-of-use standpoint, just (also) having the permissions here would help customers.
