### ISSUE TITLE
How mount the ca file for oneagent

### ISSUE THREAD

**Issue by ccheng911** [Dynatrace/dynatrace-oneagent-operator#58]
Hi, dynatrace-oneagent-operator developers.

I started up oneagent in my private env. The dynatrace server SSL is using private ca file which is not include in the oneagent image. 

I set the `skipCertCheck: true` for prohibit the ssl error. But I don't think it is really solve the problem because cert check should be need.

Cloud I mount the ca file fold (/etc/ssl/**) into the deamonset.

Thank you.

**Comment by ccheng911** [comment]
Thank you for your answer.

> Adding the right CA to /etc/ssl/certs/ca-certificates.crt should do the trick. 

Cloud I mount the ` /etc/ssl/certs/` whole folder to pod by edit cr.yaml ?

**Comment by baichinger** [comment]
No, this is not possible. This needs to be done by adjusting the deployment manifest of operator.

**Comment by ccheng911** [comment]
@baichinger 

Thank you for your reply.
