### ISSUE TITLE
How make the priorityClassName work

### ISSUE THREAD

**Issue by ccheng911** [Dynatrace/dynatrace-oneagent-operator#59]
Hi, dynatrace-oneagent-operator developers.

I have a question which is about how make the priorityClassName work.

I want to safely run oneagent on my cluster. I need make sure the oneagent pod isn't killed even OOM is happened. 

I set the `priorityClassName: system-cluster-critical` parameter in cr.yaml file and deployed it on kubernetes cluster. But I found it isn't work, `priority: 0` still set. 

How can I up the oneagent pod priority level on my cluster?

Thank you.

**Comment by baichinger** [comment]
Hi! This feature not yet implemented in the CR. As of now `priorityClassName` needs to be set in the corresponding DaemonSet.

**Comment by ccheng911** [comment]
@baichinger 

Thank you for your answer.
Your means is I need edit the Deamonset to add priorityClassName property ?

It is difficult to execute in my company. Because I admin the hundreds of clusters. I could not to add the priorityClassName property for each cluster.

**Comment by baichinger** [comment]
> Your means is I need edit the Deamonset to add priorityClassName property ?

Unfortunately, yes.

**Comment by baichinger** [comment]
> I want to safely run oneagent on my cluster. I need make sure the oneagent pod isn't killed even OOM is happened.

Configuring quality of service for OneAgent pods is supported by adding resource requests/limits to the CR. Please be aware that tight limits might cause problems as well.

> I set the `priorityClassName: system-cluster-critical` parameter in cr.yaml file and deployed it on kubernetes cluster. But I found it isn't work, `priority: 0` still set.

IMO, setting `priorityClassName` does not prevent eviction by OOM.

**Comment by ccheng911** [comment]
@baichinger

Thank you for your reply.

But I cloud not agree on `IMO, setting priorityClassName does not prevent eviction by OOM.`.
Of cource, it is not 100% habit the OOM happen. But it could decrease the probability of OOM .
