### ISSUE TITLE
allow to specify mount for install path

### ISSUE THREAD

**Issue by DJRickyB** [Dynatrace/dynatrace-oneagent-operator#63]
understood that we can't change the install_path parameter for oneagent, but what about specifying a mount path for the Daemonset for /opt/dynatrace? would be very nice for those of us with not a lot of space on /opt on the nodes...

**Comment by baichinger** [comment]
You might want to give `ONEAGENT_ENABLE_VOLUME_STORAGE` option a try. Beware, this feature is still in EAP and subject to change. It basically uses a Docker volume for all its data.

Details can be found at https://www.dynatrace.com/support/help/shortlink/gke-clusters-deploy#expand-131parameter-for-container-optimized-os-early-access.
