### ISSUE TITLE
Update to description for CR definition

### ISSUE THREAD

**Issue by tdk2fe** [Dynatrace/dynatrace-oneagent-operator#73]
On line 10, the _apiUrl_ parameter has a string with `ENVIRONMENTID` in the URL.  The description should call out that you should update this before running the manifest to create the custom resource.

**Comment by esukram** [comment]
Created #107 to reflect this issue.

**Comment by esukram** [comment]
Merged into `master` only. So the upcoming releases will have that in. Will not merge it back into current release branches.

Hope this is fine for you @tdk2fe 

Markus
