### ISSUE TITLE
oneagent operator deploys oneagent pods with broken readiness probes

### ISSUE THREAD

**Issue by MichaelMeelisRTL** [Dynatrace/dynatrace-oneagent-operator#90]
After installing releases v0.3.0 the oneagent pods are not ready we get the kubernetes event:
Readiness probe failed: grep: /proc/*/stat: No such file or directory
I see that this is fixed in the master branch but not yet in the v0.3.0 release.

**Comment by MichaelMeelisRTL** [comment]
Apparently this was

**Comment by esukram** [comment]
@MichaelMeelisRTL are you sure that you didn't use the master branch (snapshot) release?

The 0.3 branch does utilize still `pgrep` as readiness check..

Thank you in advance.

**Comment by MichaelMeelisRTL** [comment]
Hi @esukram,
You are right something went wrong with our deployments and this showed up. I will close this ticket.

**Comment by esukram** [comment]
Thank you, for your quick response!
