### ISSUE TITLE
Creating Helm Chart

### ISSUE THREAD

**Issue by Joerg-L** [Dynatrace/dynatrace-oneagent-operator#97]
For
- automated deployment
- simple release update

of Dynatrace Oneagent Operator it would be very helpfull if a working helm chart would be provided which can be parameterize minimum for

- image name
- image tag
- apiToken
- passToken
- apiUrl
- install_path
- APP_LOG_CONTENT_ACCESS

**Comment by DTMad** [comment]
Hey!

We now have a Helm Chart for the Dynatrace OneAgent Operator:
https://github.com/Dynatrace/helm-charts/tree/master/dynatrace-oneagent-operator

Feel free to use it and let us if you need help with it.

Thanks!
